# example file

spring.application.name=collaborative-code-editor

spring.data.mongodb.uri=YOUR_MONGODB_URI

spring.security.oauth2.client.registration.github.client-id=YOUR_GITHUB_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=YOUR_GITHUB_CLIENT_SECRET
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/github
spring.security.oauth2.client.registration.github.scope=repo,write:repo_hook,public_repo,delete_repo

jwt.secret=YOUR_JWT_SECRET

spring.redis.host=YOUR_REDIS_HOST
spring.redis.port=YOUR_REDIS_PORT
spring.redis.username=YOUR_REDIS_USERNAME
spring.redis.password=YOUR_REDIS_PASSWORD

server.servlet.session.timeout=30m
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.http-only=true
